### ISSUE TITLE
[전체] 최종 데모데이 지원 요청 - 이벤트

### ISSUE THREAD

**Issue by kang-hyungu** [woowacourse/working-scholars#113]
# 개요

데모데이에 진행할 이벤트를 기획 및 진행한다.

# 기간
~ 10.25(금)

# 방법

데모데이 당일 라이트닝 토크와 스탬프 투어를 진행한다.

## 1.라이트닝 토크

- [x] [라이트닝 토크 참가자 모집](https://github.com/woowacourse/working-scholars/issues/113#issuecomment-2413064755)
- [x] 라이트닝 토크 타임 테이블 준비
- [x] 라이트닝 토크 진행 

### 기획

- [x] [스탬프 투어 진행 기획](https://github.com/woowacourse/working-scholars/issues/113#issuecomment-2413135272)

### 물품 준비   
  
- [x] [스탬프 투어 도장 재사용 요청](https://github.com/woowacourse/working-scholars/issues/113#issuecomment-2421613690)
- [x] [스탬프 투어 용지 주문 요청](https://github.com/woowacourse/working-scholars/issues/113#issuecomment-2418647910)
- [ ] 선착순 상품 준비
- [ ] 스탬프 투어 진행 

# 참고 사항

**Comment by kang-hyungu** [comment]
- [x] 어떤 이벤트를 진행할 것인지 정한다.
  - 진행자가 필요하다면 지정한다.
- [ ] 행사 당일 이벤트를 진행한다.
  - [[전체] 최종 데모데이 지원 요청 - 공간 운영 방안 결정 & 자리 배치 & 다과](https://github.com/woowacourse/working-scholars/issues/114#issuecomment-2399179344) 코멘트 참고

**Comment by zangsu** [comment]
## 라이트닝 토크

라이트닝 토크 발표자 모집 완료 (8명)

<img width="745" alt="image" src="https://github.com/user-attachments/assets/252aee74-dfe6-4601-b9a8-22d946f41213">

## 발표자 및 발표 주제

폴라 - 데이터베이스 3번 바꾼 썰 푼다
로빈 - 우테코에서의 성장 경험
테바 - 낭만개발자로 성장하기
아르 - Github Actions와 AWS를 연계한 프론트엔드 CI/CD 구축기
쿠키 - 우테코에서 키워온 나만의 알맹이
짱수 - 쏟아지는 일들을 잘 쳐내기
오둥이 - 포케로그 헬퍼팀 DI 프레임워크 도입기
심지 - 안드로이드 로깅 - 빅쿼리

타임 테이블을 오전 / 오후 부스 운영을 최대한 고려할 예정입니다.

**Comment by jminkkk** [comment]
### 스탬프 투어 상품 배부

- 선착순 9개의 스탬프를 받을 경우, 상품 수령 가능
- 오전/오후를 나누어 각각 선착순

### 스탬프 투어 상품 수령 시간

- 오전 12:30 ~ 13:00
- 오후 4:00 ~ 4:30

**Comment by jminkkk** [comment]
### 라이트닝 토크 세션 시간

- 오전 11:00 ~ 12:00
- 오후 2:30 ~ 3:30

발표자는 총 8명으로 1명 당 질의응답 시간을 포함하여 총 15분으로 진행한다.

**Comment by zangsu** [comment]
# 라이트닝 토크 유튜브 업로드 구상
##  문의 결과
라이트닝 토크는 업로드에 적절하지 않다고 판단.
오프라인 대상으로만 라이트닝토크를 진행한다.

**Comment by dwax1324** [comment]
## 데모데이 스탬프 투어 종이 주문 요청

- 구매 링크: [레드프린팅 > 특가 엽서](https://www.redprinting.co.kr/ko/product/item/PR/PRCAXPO)
- 방향: **세로**
- 용지: **랑데뷰울트라화이트**
- 용지/g수: **240g**
- 규격: **100mm X 150mm**
 - 디자인 수: **1건**
- 수량: **240장**
- 파일 업로드: **pdf only**,  [6th_demo_stamp_tour_sheet.pdf](https://github.com/user-attachments/files/17428548/6th_demo_stamp_tour_sheet.pdf)


청구 금액: **56,760원**



## 주문시 파일 업로드 방법

<img width="574" alt="Screenshot 2024-10-18 at 14 23 23" src="https://github.com/user-attachments/assets/9ab6e6c4-395f-4b40-be73-1cdb44958f39">

#### - 방법1. `pdf only` 클릭 후   [6th_demo_stamp_tour_sheet.pdf](https://github.com/user-attachments/files/17428548/6th_demo_stamp_tour_sheet.pdf) 업로드

#### - 방법2. 편집하기 클릭 -> 편집 창으로 이동 후 (아래 화면)에서 `pdf 업로드` 선택 -> [6th_demo_stamp_tour_sheet.pdf](https://github.com/user-attachments/files/17428548/6th_demo_stamp_tour_sheet.pdf) 업로드

<img width="1278" alt="Screenshot 2024-10-18 at 14 27 48" src="https://github.com/user-attachments/assets/f900010c-1bd0-4584-bf37-79cefcd02ae2">

**2.1** 아래  `1 / 앞면`을 누른 후 왼쪽 사이드바의 스탬프 지도 그림   더블클릭
**2.2** 아래  `1 / 뒷면`을 누른 후 왼쪽 사이드바의 행사장 지도 그림  더블클릭
**2.3** 편집 완료 버튼 클릭!

**Comment by dwax1324** [comment]
# 작년 스탬프 투어 도장 요청

잠실캠퍼스에 있는 **내가 해냄 스탬프**를 사용한다.
<img width="383" alt="Screenshot 2024-10-18 at 16 10 00" src="https://github.com/user-attachments/assets/3aa73ba3-2a9a-48d6-bca4-fc7e807aded5">

**Comment by jminkkk** [comment]
# 스탬프 투어 상품

부스 스탬프 투어를 완료 할 경우, 스타벅스 만원 상품권 카드를 현장에서 선착순으로 배부

총 금액은 30만원으로, 오전 오후 15장씩 총 30장 상품권 제공
